version: '3.7'
services:
    oracle_db:
        image: container-registry.oracle.com/database/enterprise:latest
        env_file:
          - ./config/oracle.env
        ports:
          - 1521:1521
        volumes:
          - oracle_db_data:/opt/oracle/oradata
          - oracle_db_backup:/opt/oracle/backup
        network_mode: "host"
        healthcheck:
            test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as SYSDBA", "@healthcheck.sql"]
            interval: 30s
            timeout: 10s
            retries: 5
volumes:
    oracle_db_data:
    oracle_db_backup:
